import '@/styles/globals.css'

export const metadata = {
  title: "Deliverize - Gustavo Henrique de Almeida Batista - 07/04/2023",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
